/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.iot.data.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BluetoothInfoData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2308746749587932620L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BluetoothInfoData\",\"namespace\":\"com.iot.data.schema\",\"fields\":[{\"name\":\"bluetoothStatus\",\"type\":[\"null\",\"boolean\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Boolean bluetoothStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BluetoothInfoData() {}

  /**
   * All-args constructor.
   * @param bluetoothStatus The new value for bluetoothStatus
   */
  public BluetoothInfoData(java.lang.Boolean bluetoothStatus) {
    this.bluetoothStatus = bluetoothStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bluetoothStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bluetoothStatus = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bluetoothStatus' field.
   * @return The value of the 'bluetoothStatus' field.
   */
  public java.lang.Boolean getBluetoothStatus() {
    return bluetoothStatus;
  }

  /**
   * Sets the value of the 'bluetoothStatus' field.
   * @param value the value to set.
   */
  public void setBluetoothStatus(java.lang.Boolean value) {
    this.bluetoothStatus = value;
  }

  /**
   * Creates a new BluetoothInfoData RecordBuilder.
   * @return A new BluetoothInfoData RecordBuilder
   */
  public static com.iot.data.schema.BluetoothInfoData.Builder newBuilder() {
    return new com.iot.data.schema.BluetoothInfoData.Builder();
  }

  /**
   * Creates a new BluetoothInfoData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BluetoothInfoData RecordBuilder
   */
  public static com.iot.data.schema.BluetoothInfoData.Builder newBuilder(com.iot.data.schema.BluetoothInfoData.Builder other) {
    return new com.iot.data.schema.BluetoothInfoData.Builder(other);
  }

  /**
   * Creates a new BluetoothInfoData RecordBuilder by copying an existing BluetoothInfoData instance.
   * @param other The existing instance to copy.
   * @return A new BluetoothInfoData RecordBuilder
   */
  public static com.iot.data.schema.BluetoothInfoData.Builder newBuilder(com.iot.data.schema.BluetoothInfoData other) {
    return new com.iot.data.schema.BluetoothInfoData.Builder(other);
  }

  /**
   * RecordBuilder for BluetoothInfoData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BluetoothInfoData>
    implements org.apache.avro.data.RecordBuilder<BluetoothInfoData> {

    private java.lang.Boolean bluetoothStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.iot.data.schema.BluetoothInfoData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bluetoothStatus)) {
        this.bluetoothStatus = data().deepCopy(fields()[0].schema(), other.bluetoothStatus);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BluetoothInfoData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.iot.data.schema.BluetoothInfoData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.bluetoothStatus)) {
        this.bluetoothStatus = data().deepCopy(fields()[0].schema(), other.bluetoothStatus);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'bluetoothStatus' field.
      * @return The value.
      */
    public java.lang.Boolean getBluetoothStatus() {
      return bluetoothStatus;
    }

    /**
      * Sets the value of the 'bluetoothStatus' field.
      * @param value The value of 'bluetoothStatus'.
      * @return This builder.
      */
    public com.iot.data.schema.BluetoothInfoData.Builder setBluetoothStatus(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.bluetoothStatus = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bluetoothStatus' field has been set.
      * @return True if the 'bluetoothStatus' field has been set, false otherwise.
      */
    public boolean hasBluetoothStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bluetoothStatus' field.
      * @return This builder.
      */
    public com.iot.data.schema.BluetoothInfoData.Builder clearBluetoothStatus() {
      bluetoothStatus = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public BluetoothInfoData build() {
      try {
        BluetoothInfoData record = new BluetoothInfoData();
        record.bluetoothStatus = fieldSetFlags()[0] ? this.bluetoothStatus : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
