/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.iot.data.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LocaleData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2303129805236578503L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocaleData\",\"namespace\":\"com.iot.data.schema\",\"fields\":[{\"name\":\"deviceCountry\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"deviceLanguage\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String deviceCountry;
  @Deprecated public java.lang.String deviceLanguage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LocaleData() {}

  /**
   * All-args constructor.
   * @param deviceCountry The new value for deviceCountry
   * @param deviceLanguage The new value for deviceLanguage
   */
  public LocaleData(java.lang.String deviceCountry, java.lang.String deviceLanguage) {
    this.deviceCountry = deviceCountry;
    this.deviceLanguage = deviceLanguage;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceCountry;
    case 1: return deviceLanguage;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceCountry = (java.lang.String)value$; break;
    case 1: deviceLanguage = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'deviceCountry' field.
   * @return The value of the 'deviceCountry' field.
   */
  public java.lang.String getDeviceCountry() {
    return deviceCountry;
  }

  /**
   * Sets the value of the 'deviceCountry' field.
   * @param value the value to set.
   */
  public void setDeviceCountry(java.lang.String value) {
    this.deviceCountry = value;
  }

  /**
   * Gets the value of the 'deviceLanguage' field.
   * @return The value of the 'deviceLanguage' field.
   */
  public java.lang.String getDeviceLanguage() {
    return deviceLanguage;
  }

  /**
   * Sets the value of the 'deviceLanguage' field.
   * @param value the value to set.
   */
  public void setDeviceLanguage(java.lang.String value) {
    this.deviceLanguage = value;
  }

  /**
   * Creates a new LocaleData RecordBuilder.
   * @return A new LocaleData RecordBuilder
   */
  public static com.iot.data.schema.LocaleData.Builder newBuilder() {
    return new com.iot.data.schema.LocaleData.Builder();
  }

  /**
   * Creates a new LocaleData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LocaleData RecordBuilder
   */
  public static com.iot.data.schema.LocaleData.Builder newBuilder(com.iot.data.schema.LocaleData.Builder other) {
    return new com.iot.data.schema.LocaleData.Builder(other);
  }

  /**
   * Creates a new LocaleData RecordBuilder by copying an existing LocaleData instance.
   * @param other The existing instance to copy.
   * @return A new LocaleData RecordBuilder
   */
  public static com.iot.data.schema.LocaleData.Builder newBuilder(com.iot.data.schema.LocaleData other) {
    return new com.iot.data.schema.LocaleData.Builder(other);
  }

  /**
   * RecordBuilder for LocaleData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocaleData>
    implements org.apache.avro.data.RecordBuilder<LocaleData> {

    private java.lang.String deviceCountry;
    private java.lang.String deviceLanguage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.iot.data.schema.LocaleData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceCountry)) {
        this.deviceCountry = data().deepCopy(fields()[0].schema(), other.deviceCountry);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.deviceLanguage)) {
        this.deviceLanguage = data().deepCopy(fields()[1].schema(), other.deviceLanguage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LocaleData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.iot.data.schema.LocaleData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.deviceCountry)) {
        this.deviceCountry = data().deepCopy(fields()[0].schema(), other.deviceCountry);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.deviceLanguage)) {
        this.deviceLanguage = data().deepCopy(fields()[1].schema(), other.deviceLanguage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'deviceCountry' field.
      * @return The value.
      */
    public java.lang.String getDeviceCountry() {
      return deviceCountry;
    }

    /**
      * Sets the value of the 'deviceCountry' field.
      * @param value The value of 'deviceCountry'.
      * @return This builder.
      */
    public com.iot.data.schema.LocaleData.Builder setDeviceCountry(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceCountry = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceCountry' field has been set.
      * @return True if the 'deviceCountry' field has been set, false otherwise.
      */
    public boolean hasDeviceCountry() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceCountry' field.
      * @return This builder.
      */
    public com.iot.data.schema.LocaleData.Builder clearDeviceCountry() {
      deviceCountry = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceLanguage' field.
      * @return The value.
      */
    public java.lang.String getDeviceLanguage() {
      return deviceLanguage;
    }

    /**
      * Sets the value of the 'deviceLanguage' field.
      * @param value The value of 'deviceLanguage'.
      * @return This builder.
      */
    public com.iot.data.schema.LocaleData.Builder setDeviceLanguage(java.lang.String value) {
      validate(fields()[1], value);
      this.deviceLanguage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceLanguage' field has been set.
      * @return True if the 'deviceLanguage' field has been set, false otherwise.
      */
    public boolean hasDeviceLanguage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'deviceLanguage' field.
      * @return This builder.
      */
    public com.iot.data.schema.LocaleData.Builder clearDeviceLanguage() {
      deviceLanguage = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public LocaleData build() {
      try {
        LocaleData record = new LocaleData();
        record.deviceCountry = fieldSetFlags()[0] ? this.deviceCountry : (java.lang.String) defaultValue(fields()[0]);
        record.deviceLanguage = fieldSetFlags()[1] ? this.deviceLanguage : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
