/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.iot.data.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserAgentActionData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4129957317614535435L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserAgentActionData\",\"namespace\":\"com.iot.data.schema\",\"fields\":[{\"name\":\"userAgent\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String userAgent;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserAgentActionData() {}

  /**
   * All-args constructor.
   * @param userAgent The new value for userAgent
   */
  public UserAgentActionData(java.lang.String userAgent) {
    this.userAgent = userAgent;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userAgent;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userAgent = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userAgent' field.
   * @return The value of the 'userAgent' field.
   */
  public java.lang.String getUserAgent() {
    return userAgent;
  }

  /**
   * Sets the value of the 'userAgent' field.
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.String value) {
    this.userAgent = value;
  }

  /**
   * Creates a new UserAgentActionData RecordBuilder.
   * @return A new UserAgentActionData RecordBuilder
   */
  public static com.iot.data.schema.UserAgentActionData.Builder newBuilder() {
    return new com.iot.data.schema.UserAgentActionData.Builder();
  }

  /**
   * Creates a new UserAgentActionData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserAgentActionData RecordBuilder
   */
  public static com.iot.data.schema.UserAgentActionData.Builder newBuilder(com.iot.data.schema.UserAgentActionData.Builder other) {
    return new com.iot.data.schema.UserAgentActionData.Builder(other);
  }

  /**
   * Creates a new UserAgentActionData RecordBuilder by copying an existing UserAgentActionData instance.
   * @param other The existing instance to copy.
   * @return A new UserAgentActionData RecordBuilder
   */
  public static com.iot.data.schema.UserAgentActionData.Builder newBuilder(com.iot.data.schema.UserAgentActionData other) {
    return new com.iot.data.schema.UserAgentActionData.Builder(other);
  }

  /**
   * RecordBuilder for UserAgentActionData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserAgentActionData>
    implements org.apache.avro.data.RecordBuilder<UserAgentActionData> {

    private java.lang.String userAgent;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.iot.data.schema.UserAgentActionData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[0].schema(), other.userAgent);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserAgentActionData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.iot.data.schema.UserAgentActionData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[0].schema(), other.userAgent);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'userAgent' field.
      * @return The value.
      */
    public java.lang.String getUserAgent() {
      return userAgent;
    }

    /**
      * Sets the value of the 'userAgent' field.
      * @param value The value of 'userAgent'.
      * @return This builder.
      */
    public com.iot.data.schema.UserAgentActionData.Builder setUserAgent(java.lang.String value) {
      validate(fields()[0], value);
      this.userAgent = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userAgent' field has been set.
      * @return True if the 'userAgent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userAgent' field.
      * @return This builder.
      */
    public com.iot.data.schema.UserAgentActionData.Builder clearUserAgent() {
      userAgent = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public UserAgentActionData build() {
      try {
        UserAgentActionData record = new UserAgentActionData();
        record.userAgent = fieldSetFlags()[0] ? this.userAgent : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
